In [4]:
import pandas as pd
import numpy as np

train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
submit=pd.read_csv('submit.csv')

train.head(2)

id                                              title           author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...    Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...  Daniel J. Flynn   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0

In [5]:
test.head(2)

id                                              title            author  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...  David Streitfeld   
1  20801  Russian warships ready to strike terrorists ne...               NaN   

                                                text  
0  PALO ALTO, Calif.  —   After years of scorning...  
1  Russian warships ready to strike terrorists ne...

In [6]:
submit.head(2)

id  label
0  20800      0
1  20801      1

In [8]:
train.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [9]:
train.shape

(20800, 5)

In [10]:
test.isnull().sum()

id          0
title     122
author    503
text        7
dtype: int64

In [11]:
test.shape

(5200, 4)

In [12]:
train.dropna(inplace=True)
test.dropna(inplace=True)


In [13]:
train.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [14]:
test.isnull().sum()

id        0
title     0
author    0
text      0
dtype: int64

In [33]:
author=[]
for i in train['author']:
    d=i.split()
    d=''.join(d)
    author.append(d)
author
train['Author']=author

In [35]:
train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1  Ever get the feeling your life circles the rou...      0   
2  Why the Truth Might Get You Fired October 29, ...      1   
3  Videos 15 Civilians Killed In Single US Airstr...      1   
4  Print \nAn Iranian woman has been sentenced to...      1   

               Author  
0        DarrellLucus  
1       DanielJ.Flynn  
2  Consortiumnews.com  
3      JessicaPurkiss  
4       HowardPortnoy

In [36]:
train.drop('author',inplace=True,axis=1)
train.head()

id                                              title  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2   2                  Why the Truth Might Get You Fired   
3   3  15 Civilians Killed In Single US Airstrike Hav...   
4   4  Iranian woman jailed for fictional unpublished...   

                                                text  label  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1  Ever get the feeling your life circles the rou...      0   
2  Why the Truth Might Get You Fired October 29, ...      1   
3  Videos 15 Civilians Killed In Single US Airstr...      1   
4  Print \nAn Iranian woman has been sentenced to...      1   

               Author  
0        DarrellLucus  
1       DanielJ.Flynn  
2  Consortiumnews.com  
3      JessicaPurkiss  
4       HowardPortnoy

In [37]:
author=[]
for name in test['author']:
    d=name.split()
    d=''.join(d)
    author.append(d)
test['Author']=author
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   
6  20806  Pelosi Calls for FBI Investigation to Find Out...   

                    author                                               text  \
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...   
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...   
3            Daniel Victor  If at first you don’t succeed, try a different...   
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...   
6                  Pam Key  Sunday on NBC’s “Meet the Press,” House Minori...   

                  Author  
0        DavidStreitfeld  
2           CommonDreams  
3           DanielVictor  
4  TruthBroadcastNetwork  
6                 PamKey

In [38]:
test.drop('author',axis=1,inplace=True)
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   
6  20806  Pelosi Calls for FBI Investigation to Find Out...   

                                                text                 Author  
0  PALO ALTO, Calif.  —   After years of scorning...        DavidStreitfeld  
2  Videos #NoDAPL: Native American Leaders Vow to...           CommonDreams  
3  If at first you don’t succeed, try a different...           DanielVictor  
4  42 mins ago 1 Views 0 Comments 0 Likes 'For th...  TruthBroadcastNetwork  
6  Sunday on NBC’s “Meet the Press,” House Minori...                 PamKey

In [39]:
#concat title an Author to content for train and test
train['content']=train['title']+' '+train['Author']
test['content']=test['title']+' '+test['Author']

In [40]:
train.head()

id                                              title  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2   2                  Why the Truth Might Get You Fired   
3   3  15 Civilians Killed In Single US Airstrike Hav...   
4   4  Iranian woman jailed for fictional unpublished...   

                                                text  label  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1  Ever get the feeling your life circles the rou...      0   
2  Why the Truth Might Get You Fired October 29, ...      1   
3  Videos 15 Civilians Killed In Single US Airstr...      1   
4  Print \nAn Iranian woman has been sentenced to...      1   

               Author                                            content  
0        DarrellLucus  House Dem Aide: We Didn’t Even See Comey’s Let...  
1       DanielJ.Flynn  FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2  Consortiumnews.com  Why the Truth Might Get You Fired Consortiumne...  
3      JessicaPurkiss  15 Civilians Killed In Single US Airstrike Hav...  
4       HowardPortnoy  Iranian woman jailed for fictional unpublished...

In [41]:
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   
6  20806  Pelosi Calls for FBI Investigation to Find Out...   

                                                text                 Author  \
0  PALO ALTO, Calif.  —   After years of scorning...        DavidStreitfeld   
2  Videos #NoDAPL: Native American Leaders Vow to...           CommonDreams   
3  If at first you don’t succeed, try a different...           DanielVictor   
4  42 mins ago 1 Views 0 Comments 0 Likes 'For th...  TruthBroadcastNetwork   
6  Sunday on NBC’s “Meet the Press,” House Minori...                 PamKey   

                                             content  
0  Specter of Trump Loosens Tongues, if Not Purse...  
2  #NoDAPL: Native American Leaders Vow to Stay A...  
3  Tim Tebow Will Attempt Another Comeback, This ...  
4  Keiser Report: Meme Wars (E995) TruthBroadcast...  
6  Pelosi Calls for FBI Investigation to Find Out...

In [42]:
train['content'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It DarrellLucus'

In [43]:
test['content'][0]

'Specter of Trump Loosens Tongues, if Not Purse Strings, in Silicon Valley - The New York Times DavidStreitfeld'

In [46]:
X=train['content']
y=train['label']

Applying one hot encoding after stemming

In [58]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [70]:
ps=PorterStemmer()
corpus=[]
for i in X:
    content=re.sub('[^a-zA-Z]',' ',i)
    content=content.lower()
    content=content.split()
    review=[ps.stem(word) for word in content if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)
corpus

['hous dem aid even see comey letter jason chaffetz tweet darrelllucu',
 'flynn hillari clinton big woman campu breitbart danielj flynn',
 'truth might get fire consortiumnew com',
 'civilian kill singl us airstrik identifi jessicapurkiss',
 'iranian woman jail fiction unpublish stori woman stone death adulteri howardportnoy',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart danielnussbaum',
 'beno hamon win french socialist parti presidenti nomin new york time alissaj rubin',
 'back channel plan ukrain russia courtesi trump associ new york time megantwoheyandscottshan',
 'obama organ action partner soro link indivis disrupt trump agenda aaronklein',
 'bbc comedi sketch real housew isi caus outrag christomlinson',
 'russian research discov secret nazi militari base treasur hunter arctic photo amandoflavio',
 'us offici see link trump russia jasonditz',
 'ye paid govern troll social media blog forum websit anotheranni',
 'major leagu so

In [73]:
from tensorflow.keras.preprocessing.text import one_hot
vocab_size=5000
one_hot_rep=[one_hot(words,vocab_size) for words in corpus]
one_hot_rep
#jis index pe word hoga in vocab uska index return krega 

[[2510, 694, 3324, 2139, 1887, 4242, 529, 2353, 2990, 760, 474],
 [4923, 2184, 2848, 2489, 2941, 3027, 267, 4161, 4923],
 [3838, 1648, 4776, 1386, 4157, 4295],
 [1215, 2667, 3647, 1804, 4311, 956, 3895],
 [1713, 2941, 4641, 846, 4567, 3077, 2941, 4818, 4073, 344, 1604],
 [1776,
  3395,
  1015,
  1481,
  1944,
  596,
  4388,
  2339,
  4504,
  3201,
  62,
  2189,
  4863,
  2144,
  267,
  3780],
 [2077, 4864, 1423, 4708, 2486, 1893, 195, 2563, 3429, 2329, 2807, 2646, 4073],
 [4239, 4587, 1050, 2214, 4589, 4202, 596, 909, 3429, 2329, 2807, 2779],
 [3233, 4662, 2171, 81, 1414, 4317, 4943, 1257, 596, 4236, 2327],
 [1221, 4369, 165, 3496, 1486, 4762, 3758, 3581, 254],
 [1866, 4112, 590, 2770, 4942, 4887, 489, 4439, 4561, 167, 2100, 2968],
 [1804, 591, 1887, 4317, 596, 4589, 4533],
 [4062, 3045, 2129, 2697, 2975, 4635, 3972, 1204, 638, 4627],
 [2134, 4835, 2584, 2091, 2459, 4689, 4583, 3429, 2329, 2807, 1368],
 [3949, 4841, 1657, 4251, 4434, 3429, 2329, 2807, 1633],
 [3284, 2339, 34, 4455, 243

In [76]:
corpus[1],one_hot_rep[1]

('flynn hillari clinton big woman campu breitbart danielj flynn',
 [4923, 2184, 2848, 2489, 2941, 3027, 267, 4161, 4923])

In [81]:
m=0
for i in one_hot_rep:
   if m<len(i):
    m=len(i)
    
print(m)
#max length of a sequence

51


In [83]:
sent_len=35
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sent=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
padded_sent

array([[   0,    0,    0, ..., 2990,  760,  474],
       [   0,    0,    0, ...,  267, 4161, 4923],
       [   0,    0,    0, ..., 1386, 4157, 4295],
       ...,
       [   0,    0,    0, ..., 2807, 2930, 4320],
       [   0,    0,    0, ..., 1295, 4071, 4450],
       [   0,    0,    0, ...,  239,  901, 1210]])

In [85]:
#creating model 
embedding_features=40

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Embedding,LSTM,Dense

In [86]:
model=Sequential()
model.add(Embedding(vocab_size,embedding_features,input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile('adam','binary_crossentropy','accuracy')

In [87]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 35, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [115]:
# model.fit(X,y,epochs=10)
X=np.array(padded_sent)
y=np.array(y)

In [93]:
model.fit(X,y,epochs=10)

Epoch 1/10
572/572 [==============================] - 12s 19ms/step - loss: 0.1266 - accuracy: 0.9456
Epoch 2/10
572/572 [==============================] - 11s 20ms/step - loss: 0.0134 - accuracy: 0.9960
Epoch 3/10
572/572 [==============================] - 11s 19ms/step - loss: 0.0043 - accuracy: 0.9986
Epoch 4/10
572/572 [==============================] - 11s 19ms/step - loss: 0.0014 - accuracy: 0.9998
Epoch 5/10
572/572 [==============================] - 10s 17ms/step - loss: 4.4052e-04 - accuracy: 0.9999
Epoch 6/10
572/572 [==============================] - 9s 16ms/step - loss: 8.4397e-05 - accuracy: 1.0000
Epoch 7/10
572/572 [==============================] - 9s 16ms/step - loss: 3.0220e-05 - accuracy: 1.0000
Epoch 8/10
572/572 [==============================] - 9s 16ms/step - loss: 1.5938e-05 - accuracy: 1.0000
Epoch 9/10
572/572 [==============================] - 11s 18ms/step - loss: 1.1244e-05 - accuracy: 1.0000
Epoch 10/10
572/572 [==============================] - 10s 17ms/s

In [96]:
X_test=test['content']

In [97]:
ps=PorterStemmer()
corpus_test=[]
for i in X_test:
    content=re.sub('[^a-zA-Z]',' ',i)
    content=content.lower()
    content=content.split()
    review=[ps.stem(word) for word in content if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus_test.append(review)
corpus_test

['specter trump loosen tongu purs string silicon valley new york time davidstreitfeld',
 'nodapl nativ american leader vow stay winter file lawsuit polic commondream',
 'tim tebow attempt anoth comeback time basebal new york time danielvictor',
 'keiser report meme war e truthbroadcastnetwork',
 'pelosi call fbi investig find russian donald trump breitbart pamkey',
 'weekli featur profil randi shannon trevorloudon',
 'u gener admir endors trump command chief dr eowyn',
 'work class hero john brennon dougdiamond',
 'rise mandatori vaccin mean end medic freedom shaunbradley',
 'communist terror small busi stevewatson',
 'comput programm come forward admit paid rig vote booth trump right usa newsflash usanewsflash',
 'thiev take chunk chang pound berlin museum new york time melissaeddi',
 'new england patriot owner still sore n f l payback sight new york time kenbelsonandbenshpigel',
 'colleg republican yaf sue berkeley ann coulter event breitbart tomciccotta',
 'trump melt accus us posta

In [131]:
vocab_size=5000
one_hot_rep_test=[one_hot(words,vocab_size) for words in corpus_test]
one_hot_rep_test

[[2529, 596, 318, 4888, 2752, 1444, 644, 975, 3429, 2329, 2807, 4929],
 [3563, 380, 1267, 2651, 4875, 116, 4848, 1227, 1011, 3487, 4989],
 [190, 253, 4392, 950, 4942, 2807, 1195, 3429, 2329, 2807, 4309],
 [128, 2226, 4528, 4049, 4616, 4264],
 [2253, 3612, 1236, 4395, 2459, 1866, 1712, 596, 267, 803],
 [1942, 1643, 4423, 577, 992, 6],
 [2669, 1690, 464, 2778, 596, 4155, 1657, 2419, 131],
 [2738, 3796, 336, 3377, 2564, 1024],
 [1746, 4234, 3228, 1005, 1609, 653, 919, 1490],
 [1777, 2156, 1249, 2520, 2386],
 [1458,
  3452,
  2861,
  2389,
  4523,
  3045,
  4868,
  3273,
  2838,
  596,
  3424,
  4376,
  2194,
  2646],
 [4505, 1788, 1848, 2159, 4771, 932, 4614, 3429, 2329, 2807, 4278],
 [3429,
  1967,
  840,
  1832,
  255,
  1083,
  1953,
  239,
  2241,
  2288,
  3272,
  3429,
  2329,
  2807,
  3926],
 [1829, 3985, 57, 2105, 4603, 2609, 2957, 4025, 267, 4577],
 [596, 1562, 2577, 1804, 3881, 4079, 3475, 3968, 2848, 3843],
 [2230, 123, 4176, 1083, 3621, 2424, 3873, 4689, 3429, 2329, 2807, 238

In [132]:
padded_sent_test=pad_sequences(one_hot_rep_test,padding='pre',maxlen=sent_len)
padded_sent_test

array([[   0,    0,    0, ..., 2329, 2807, 4929],
       [   0,    0,    0, ..., 1011, 3487, 4989],
       [   0,    0,    0, ..., 2329, 2807, 4309],
       ...,
       [   0,    0,    0, ..., 2329, 2807, 2076],
       [   0,    0,    0, ..., 2329, 2807, 3640],
       [   0,    0,    0, ..., 2329, 2807, 1384]])

In [133]:
X_test=np.array(padded_sent_test)
X_test

array([[   0,    0,    0, ..., 2329, 2807, 4929],
       [   0,    0,    0, ..., 1011, 3487, 4989],
       [   0,    0,    0, ..., 2329, 2807, 4309],
       ...,
       [   0,    0,    0, ..., 2329, 2807, 2076],
       [   0,    0,    0, ..., 2329, 2807, 3640],
       [   0,    0,    0, ..., 2329, 2807, 1384]])

In [134]:
y_pred=model.predict(X_test)
y_pred

143/143 [==============================] - 1s 6ms/step


array([[1.7505442e-08],
       [9.9999315e-01],
       [1.0391461e-10],
       ...,
       [3.8056327e-09],
       [1.6606023e-09],
       [2.2702475e-08]], dtype=float32)

In [135]:
y_hat=np.where(y_pred>0.6,1,0)

In [136]:
y_hat.shape

(4575, 1)

In [138]:
y_hat=y_hat.reshape(4575,)
y_hat

array([0, 1, 0, ..., 0, 0, 0])

In [151]:
sub=test['id']
sub=pd.DataFrame(sub)
sub['label']=y_hat
sub.head()
# y_hat.shape,test.shape

id  label
0  20800      0
2  20802      1
3  20803      0
4  20804      1
6  20806      0

In [152]:
sub.to_csv('submission.csv',index=False)